#!/bin/bash
RED="\e[1;31m"
GREEN="\e[1;32m"
BLUE="\e[1;34m"
WHITE="\e[1;97m"
YELLOW="\e[1;93m"
NORMAL="\e[1;0m"

function help {
   	printf "\n\nUsage: ${WHITE}./cp-tpl template destination name${NORMAL}"
	printf "\n\n\t${YELLOW}template${NORMAL}: template basename\n"
	printf "\t${YELLOW}destination${NORMAL}: path to create project\n"
	printf "\t${YELLOW}name${NORMAL}: name of the project to create\n"
}

TPL=$1
CREATION_PATH=${2%/}
NAME=$3
ERROR=0
#testing vars
if [ -z "$TPL" ]
	then
		printf "\n${RED}Template is missing${NORMAL}"
		ERROR=1
fi;
if [ -z "$CREATION_PATH" ]
	then
		printf "\n${RED}Path is missing${NORMAL}"
		ERROR=1
fi;

if [ -z "$NAME" ]
	then
		printf "\n${RED}Name is missing${NORMAL}"
		ERROR=1
fi;

if [ $ERROR -eq 1 ]
	then
		help
		printf "\n"
		exit 1
fi

if [ ! -e "$TPL.yml" ]
	then
		printf "${RED}Template $TPL.yml doesn't exists${NORMAL}\n"
		exit 1
fi;

if [ ! -e "$CREATION_PATH" ]
	then
		while true; do
			printf "\n${RED}Folder \"$CREATION_PATH\" doesn't exists${NORMAL}\n"
		    read -p "Do you wish to create it?  (y/n)  " yn
		    case $yn in
		        [Yy]* ) break;;
		        [Nn]* ) printf "\n${RED}Folder \"$CREATION_PATH\" doesn't exists, can't continue${NORMAL}\n";exit 1;;
		        * ) echo "Please answer yes or no.";;
		    esac
		done
fi;

if [ -f "$CREATION_PATH/$NAME.yml" ]
	then
		printf "\n${RED}The file $CREATION_PATH/$NAME.yml already exists${NORMAL}\n"
		while true; do
			printf "\n"
		    read -p "Do you wish to overwrite this file? (y/n) " yn
		    case $yn in
		        [Yy]* ) break;;
		        [Nn]* ) printf "\nCreation canceled\n";exit 1;;
		        * ) echo "Please answer yes or no.";;
		    esac
		done
fi;

mkdir -p $CREATION_PATH

if [ ! -d "$CREATION_PATH/" ]
	then
		printf "${RED}Can't create $CREATION_PATH/ folder${NORMAL}"
		printf "\n\n"
		exit 1;
fi;

cp $TPL.yml $CREATION_PATH/$NAME.yml
cp ${TPL}_env $CREATION_PATH/${NAME}_env

printf "\n${GREEN}Project created.\n\n${NORMAL}Edit the ${WHITE}${CREATION_PATH}/${NAME}_env${NORMAL} file and then run:"
printf "\n\n${WHITE}\t./use-tpl ${YELLOW}[create|up]${WHITE} $CREATION_PATH/$NAME ${NORMAL}\n\n"

