#!/bin/bash
RED="\e[1;31m"
GREEN="\e[1;32m"
BLUE="\e[1;34m"
WHITE="\e[1;97m"
YELLOW="\e[1;93m"
NORMAL="\e[1;0m"

function help {
   	printf "${BLUE}\n./docker-create ${YELLOW}action name${NORMAL}"
	printf "\n\n\t${YELLOW}action${NORMAL}: create or up\n"
	printf "\t${YELLOW}name${NORMAL}: name of the project\n\n"
}

ACTION=$1
NAME=$2
ERROR=0
#testing vars
if [ -z "$ACTION" ]
	then
		printf "${RED}Action is missing${NORMAL}"
		ERROR=1
	else
		OPTIONS=("create" "up")
		ACTION_EXISTS=$(echo ${OPTIONS[@]} | grep -o "$ACTION" | wc -w)
		if [ $ACTION_EXISTS -eq 0 ]
			then
				printf "${RED}Action must be ${YELLOW}create${RED} or ${YELLOW}up${NORMAL}"
				ERROR=1
			fi;
fi;
if [ -z "$NAME" ]
	then
		printf "\n${RED}Name is missing${NORMAL}"
		ERROR=1
	else
	if [ ! -e "./containers/$NAME/$NAME.yml" ]
		then
			printf "\n${RED}The project \"$NAME\" doesn't exists${NORMAL}"
			ERROR=1
	fi;
fi;
if [ $ERROR -eq 1 ]
	then
		printf "\n"
		help
		exit 1
fi
command -v docker-compose >/dev/null 2>&1 || { printf "\n${RED}docker-compose not found. Aborting.${NORMAL}\n\n" >&2; exit 1; }
DOCKER_COMPOSE=`command -v docker-compose`
COMPOSE_VERSION=`docker-compose -v`
printf "\n\n${GREEN}Using:${NORMAL} $COMPOSE_VERSION\n\n"

source "./containers/$NAME/$NAME.env"

$DOCKER_COMPOSE -f  "./containers/$NAME/$NAME.yml" $ACTION